#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AlarmInterface

#include "Basic.hpp"

#include "AlarmInterface_classes.hpp"


namespace SDK
{

// Function AlarmInterface.AlarmInterface_C.AlarmTriggeredInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void IAlarmInterface_C::AlarmTriggeredInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("AlarmInterface_C", "AlarmTriggeredInterfaceCall");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function AlarmInterface.AlarmInterface_C.AlarmDisabledInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void IAlarmInterface_C::AlarmDisabledInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("AlarmInterface_C", "AlarmDisabledInterfaceCall");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function AlarmInterface.AlarmInterface_C.OnAllPowerboxesDestroyed
// (Public, BlueprintCallable, BlueprintEvent)

void IAlarmInterface_C::OnAllPowerboxesDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("AlarmInterface_C", "OnAllPowerboxesDestroyed");

	AsUObject()->ProcessEvent(Func, nullptr);
}

}

