#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AlertComponent

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AlertComponent.AlertComponent_C
// 0x0028 (0x00D8 - 0x00B0)
class UAlertComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void()>              OnAlarmtriggered;                                  // 0x00B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FVector& Location, float InvestigationDuration)> NearbyNoise; // 0x00C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_AlertComponent(int32 EntryPoint);
	void AlertNearestGuard(const struct FVector& AlertLocation);
	void ForceAlarm();
	void TriggerAlarm();
	void AlertNearbyGuards(float max_distance, bool MustBeVisible_, const struct FVector& Location, float Duration);
	void OnAlarm();
	void ReceiveBeginPlay();
	void AlertAllGuards(const class FString& Alert_reason);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AlertComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AlertComponent_C")
	}
	static class UAlertComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAlertComponent_C>();
	}
};
DUMPER7_ASSERTS_UAlertComponent_C;

}

