#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Attachment_mag_CX9_Extended

#include "Basic.hpp"

#include "Attachment_mag_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Attachment_mag_CX9_Extended.Attachment_mag_CX9_Extended_C
// 0x0000 (0x0250 - 0x0250)
class AAttachment_mag_CX9_Extended_C final : public AAttachment_mag_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Attachment_mag_CX9_Extended_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Attachment_mag_CX9_Extended_C")
	}
	static class AAttachment_mag_CX9_Extended_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAttachment_mag_CX9_Extended_C>();
	}
};
DUMPER7_ASSERTS_AAttachment_mag_CX9_Extended_C;

}

