#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AmbienceSoundController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AmbienceSoundController.BP_AmbienceSoundController_C
// 0x0030 (0x0250 - 0x0220)
class ABP_AmbienceSoundController_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             OutsideAmbience;                                   // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UAudioComponent*                        AmbientSoundComponent;                             // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MusicPlaying_;                                     // 0x0240(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        Music;                                             // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AmbienceSoundController(int32 EntryPoint);
	void StartMusic();
	void AlarmTriggeredInterfaceCall();
	void StartSound(class APlayerCharacter_C* Player);
	void StopOutsideSound(class APlayerCharacter_C* Player);
	void ReceiveBeginPlay();
	void OnAllPowerboxesDestroyed();
	void AlarmDisabledInterfaceCall();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AmbienceSoundController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AmbienceSoundController_C")
	}
	static class ABP_AmbienceSoundController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AmbienceSoundController_C>();
	}
};
DUMPER7_ASSERTS_ABP_AmbienceSoundController_C;

}

