#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarValueOverlapper

#include "Basic.hpp"

#include "Money_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CarValueOverlapper.BP_CarValueOverlapper_C
// 0x0008 (0x0270 - 0x0268)
class ABP_CarValueOverlapper_C final : public AMoney_base_C
{
public:
	class UBoxComponent*                          Box;                                               // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CarValueOverlapper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CarValueOverlapper_C")
	}
	static class ABP_CarValueOverlapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CarValueOverlapper_C>();
	}
};
DUMPER7_ASSERTS_ABP_CarValueOverlapper_C;

}

