#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Powerbox

#include "Basic.hpp"

#include "BP_Powerbox_classes.hpp"
#include "BP_Powerbox_parameters.hpp"


namespace SDK
{

// Function BP_Powerbox.BP_Powerbox_C.ExecuteUbergraph_BP_Powerbox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Powerbox_C::ExecuteUbergraph_BP_Powerbox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "ExecuteUbergraph_BP_Powerbox");

	Params::BP_Powerbox_C_ExecuteUbergraph_BP_Powerbox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Powerbox.BP_Powerbox_C.SabotageFloatingWarning
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::SabotageFloatingWarning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "SabotageFloatingWarning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.AlarmTriggeredInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::AlarmTriggeredInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "AlarmTriggeredInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.DisablePowerboxMulti
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::DisablePowerboxMulti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "DisablePowerboxMulti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.DisablePowerBoxServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::DisablePowerBoxServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "DisablePowerBoxServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.FinishDestroyMulti
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::FinishDestroyMulti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "FinishDestroyMulti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.FinishDestroyServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::FinishDestroyServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "FinishDestroyServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.BndEvt__Powerbox_Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Powerbox_C::BndEvt__Powerbox_Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "BndEvt__Powerbox_Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_Powerbox_C_BndEvt__Powerbox_Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Powerbox.BP_Powerbox_C.ShortBoxServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Powerbox_C::ShortBoxServer(class AActor* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "ShortBoxServer");

	Params::BP_Powerbox_C_ShortBoxServer Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Powerbox.BP_Powerbox_C.ShortBoxMulti
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::ShortBoxMulti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "ShortBoxMulti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.OpenBox
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::OpenBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "OpenBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.BndEvt__Powerbox_InteractComponent_K2Node_ComponentBoundEvent_1_Interact__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Powerbox_C::BndEvt__Powerbox_InteractComponent_K2Node_ComponentBoundEvent_1_Interact__DelegateSignature(class AActor* Player, class UPrimitiveComponent* HitComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "BndEvt__Powerbox_InteractComponent_K2Node_ComponentBoundEvent_1_Interact__DelegateSignature");

	Params::BP_Powerbox_C_BndEvt__Powerbox_InteractComponent_K2Node_ComponentBoundEvent_1_Interact__DelegateSignature Parms{};

	Parms.Player = Player;
	Parms.HitComponent = HitComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Powerbox.BP_Powerbox_C.HighlightBoxesOnAlarm
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::HighlightBoxesOnAlarm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "HighlightBoxesOnAlarm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.OnAllPowerboxesDestroyed
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::OnAllPowerboxesDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "OnAllPowerboxesDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.AlarmDisabledInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::AlarmDisabledInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "AlarmDisabledInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.CheckIfAllDoorsArelocked
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   ShouldHighlight_                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Powerbox_C::CheckIfAllDoorsArelocked(bool* ShouldHighlight_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "CheckIfAllDoorsArelocked");

	Params::BP_Powerbox_C_CheckIfAllDoorsArelocked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldHighlight_ != nullptr)
		*ShouldHighlight_ = Parms.ShouldHighlight_;
}


// Function BP_Powerbox.BP_Powerbox_C.HighlightNextPowerbox
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Powerbox_C::HighlightNextPowerbox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "HighlightNextPowerbox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Powerbox.BP_Powerbox_C.CheckIfAllDestroyed
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   AllDestroyed_                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Powerbox_C::CheckIfAllDestroyed(bool* AllDestroyed_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Powerbox_C", "CheckIfAllDestroyed");

	Params::BP_Powerbox_C_CheckIfAllDestroyed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AllDestroyed_ != nullptr)
		*AllDestroyed_ = Parms.AllDestroyed_;
}

}

