#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SoundOcclusionComponent

#include "Basic.hpp"

#include "BP_SoundOcclusionComponent_classes.hpp"
#include "BP_SoundOcclusionComponent_parameters.hpp"


namespace SDK
{

// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.ExecuteUbergraph_BP_SoundOcclusionComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SoundOcclusionComponent_C::ExecuteUbergraph_BP_SoundOcclusionComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "ExecuteUbergraph_BP_SoundOcclusionComponent");

	Params::BP_SoundOcclusionComponent_C_ExecuteUbergraph_BP_SoundOcclusionComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.StopSound
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UBP_SoundOcclusionComponent_C::StopSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "StopSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.StartSound
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Attach                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SoundOcclusionComponent_C::StartSound(class USoundBase* Sound, class USceneComponent* Attach)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "StartSound");

	Params::BP_SoundOcclusionComponent_C_StartSound Parms{};

	Parms.Sound = Sound;
	Parms.Attach = Attach;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SoundOcclusionComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "ReceiveTick");

	Params::BP_SoundOcclusionComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.TracePlayer
// (BlueprintCallable, BlueprintEvent)

void UBP_SoundOcclusionComponent_C::TracePlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "TracePlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.PlaySoundAtLocation
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   VolumeMultiplier                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   PitchMultiplier                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SoundOcclusionComponent_C::PlaySoundAtLocation(class USoundBase* Sound, const struct FVector& Location_0, float VolumeMultiplier, float PitchMultiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "PlaySoundAtLocation");

	Params::BP_SoundOcclusionComponent_C_PlaySoundAtLocation Parms{};

	Parms.Sound = Sound;
	Parms.Location_0 = std::move(Location_0);
	Parms.VolumeMultiplier = VolumeMultiplier;
	Parms.PitchMultiplier = PitchMultiplier;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SoundOcclusionComponent.BP_SoundOcclusionComponent_C.TraceToPlayer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_SoundOcclusionComponent_C::TraceToPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundOcclusionComponent_C", "TraceToPlayer");

	UObject::ProcessEvent(Func, nullptr);
}

}

