#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TowSpline

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TowSpline.BP_TowSpline_C
// 0x0008 (0x0228 - 0x0220)
class ABP_TowSpline_C final : public AActor
{
public:
	class USplineComponent*                       Spline;                                            // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TowSpline_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TowSpline_C")
	}
	static class ABP_TowSpline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TowSpline_C>();
	}
};
DUMPER7_ASSERTS_ABP_TowSpline_C;

}

