#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChatMessageChild

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChatMessageChild.ChatMessageChild_C
// 0x0058 (0x02B8 - 0x0260)
class UChatMessageChild_C final : public UUserWidget
{
public:
	class UTextBlock*                             Chat;                                              // 0x0260(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Name_0;                                            // 0x0268(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 ChatName;                                          // 0x0270(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 ChatMessage;                                       // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FSlateColor                            MessageColor;                                      // 0x0290(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	class FText Get_Name_Text_0();
	class FText Get_Chat_Text_0();
	struct FSlateColor Get_Chat_ColorAndOpacity_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChatMessageChild_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChatMessageChild_C")
	}
	static class UChatMessageChild_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChatMessageChild_C>();
	}
};
DUMPER7_ASSERTS_UChatMessageChild_C;

}

