#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EmoteBPBase_Guitar

#include "Basic.hpp"

#include "EmoteBPBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EmoteBPBase_Guitar.EmoteBPBase_Guitar_C
// 0x0010 (0x0250 - 0x0240)
class AEmoteBPBase_Guitar_C final : public AEmoteBPBase_C
{
public:
	class UAudioComponent*                        Audio;                                             // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EmoteBPBase_Guitar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EmoteBPBase_Guitar_C")
	}
	static class AEmoteBPBase_Guitar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEmoteBPBase_Guitar_C>();
	}
};
DUMPER7_ASSERTS_AEmoteBPBase_Guitar_C;

}

