#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Floor_Ceiling

#include "Basic.hpp"

#include "BP_Wall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Floor_Ceiling.Floor_Ceiling_C
// 0x0008 (0x0288 - 0x0280)
class AFloor_Ceiling_C final : public ABP_Wall_C
{
public:
	uint8                                         Pad_279[0x3];                                      // 0x0279(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FloorDimension;                                    // 0x027C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         Width;                                             // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Floor_Ceiling_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Floor_Ceiling_C")
	}
	static class AFloor_Ceiling_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFloor_Ceiling_C>();
	}
};
DUMPER7_ASSERTS_AFloor_Ceiling_C;

}

