#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Grip_Pistol_Long

#include "Basic.hpp"

#include "Attachment_Grip_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Grip_Pistol_Long.Grip_Pistol_Long_C
// 0x0000 (0x0250 - 0x0250)
class AGrip_Pistol_Long_C final : public AAttachment_Grip_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Grip_Pistol_Long_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Grip_Pistol_Long_C")
	}
	static class AGrip_Pistol_Long_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGrip_Pistol_Long_C>();
	}
};
DUMPER7_ASSERTS_AGrip_Pistol_Long_C;

}

