#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GuardInterface

#include "Basic.hpp"


namespace SDK::Params
{

// Function GuardInterface.GuardInterface_C.FindNearestGuardAsActor
// 0x0010 (0x0010 - 0x0000)
struct GuardInterface_C_FindNearestGuardAsActor final
{
public:
	class AActor*                                 GuardActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Distance;                                          // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GuardInterface_C_FindNearestGuardAsActor;

}

