#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HackingGame_ButtonMash

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HackingGame_base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HackingGame_ButtonMash.HackingGame_ButtonMash_C
// 0x0030 (0x0298 - 0x0268)
class UHackingGame_ButtonMash_C final : public UHackingGame_base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       BreakWall;                                         // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                Button_54;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CrackImage;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_0;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         Progress;                                          // 0x0290(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HackingGame_ButtonMash(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	void BndEvt__HackingGame_ButtonMash_Button_54_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HackingGame_ButtonMash_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HackingGame_ButtonMash_C")
	}
	static class UHackingGame_ButtonMash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHackingGame_ButtonMash_C>();
	}
};
DUMPER7_ASSERTS_UHackingGame_ButtonMash_C;

}

