#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HitchComponent

#include "Basic.hpp"

#include "HitchComponent_classes.hpp"
#include "HitchComponent_parameters.hpp"


namespace SDK
{

// Function HitchComponent.HitchComponent_C.ExecuteUbergraph_HitchComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHitchComponent_C::ExecuteUbergraph_HitchComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "ExecuteUbergraph_HitchComponent");

	Params::HitchComponent_C_ExecuteUbergraph_HitchComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HitchComponent.HitchComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UHitchComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.HalfTowSpeedServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::HalfTowSpeedServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "HalfTowSpeedServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.AttachHitch
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_HitchHook_C*                  Hitch                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHitchComponent_C::AttachHitch(class ABP_HitchHook_C* Hitch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "AttachHitch");

	Params::HitchComponent_C_AttachHitch Parms{};

	Parms.Hitch = Hitch;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HitchComponent.HitchComponent_C.HitchMulticast
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_HitchHook_C*                  Hitch                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHitchComponent_C::HitchMulticast(class ABP_HitchHook_C* Hitch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "HitchMulticast");

	Params::HitchComponent_C_HitchMulticast Parms{};

	Parms.Hitch = Hitch;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HitchComponent.HitchComponent_C.MoveAlongSpline
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::MoveAlongSpline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "MoveAlongSpline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHitchComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "ReceiveTick");

	Params::HitchComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HitchComponent.HitchComponent_C.UpdateSplineDistance
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::UpdateSplineDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "UpdateSplineDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.OnAllPowerboxesDestroyed
// (Public, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::OnAllPowerboxesDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "OnAllPowerboxesDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.AlarmDisabledInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::AlarmDisabledInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "AlarmDisabledInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HitchComponent.HitchComponent_C.AlarmTriggeredInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void UHitchComponent_C::AlarmTriggeredInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HitchComponent_C", "AlarmTriggeredInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}

}

