#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IM1

#include "Basic.hpp"

#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IM1.IM1_C
// 0x0018 (0x0348 - 0x0330)
class AIM1_C final : public AGunBase_C
{
public:
	class UBoxComponent*                          CollisionBox2;                                     // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          CollisionBox1;                                     // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Scope_front;                                       // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("IM1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IM1_C")
	}
	static class AIM1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIM1_C>();
	}
};
DUMPER7_ASSERTS_AIM1_C;

}

