#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InstructionInterface

#include "Basic.hpp"

#include "InstructionStruct_structs.hpp"


namespace SDK::Params
{

// Function InstructionInterface.InstructionInterface_C.AnnounceNewInstructionWidget
// 0x0010 (0x0010 - 0x0000)
struct InstructionInterface_C_AnnounceNewInstructionWidget final
{
public:
	class FString                                 Title;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_InstructionInterface_C_AnnounceNewInstructionWidget;

// Function InstructionInterface.InstructionInterface_C.GetCurrentInstruction
// 0x0030 (0x0030 - 0x0000)
struct InstructionInterface_C_GetCurrentInstruction final
{
public:
	struct FInstructionStruct                     Instruction;                                       // 0x0000(0x0030)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_InstructionInterface_C_GetCurrentInstruction;

}

