#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InventoryCategoryTitle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShopItemCategory_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass InventoryCategoryTitle.InventoryCategoryTitle_C
// 0x0020 (0x0280 - 0x0260)
class UInventoryCategoryTitle_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Highligh;                                          // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_59;                                      // 0x0270(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EShopItemCategory                             Category;                                          // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          NoItems_;                                          // 0x0279(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_InventoryCategoryTitle(int32 EntryPoint);
	void HighlightCategory();
	class FText GetText_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("InventoryCategoryTitle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InventoryCategoryTitle_C")
	}
	static class UInventoryCategoryTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInventoryCategoryTitle_C>();
	}
};
DUMPER7_ASSERTS_UInventoryCategoryTitle_C;

}

