#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadingUI

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoadingUI.LoadingUI_C
// 0x0000 (0x0260 - 0x0260)
class ULoadingUI_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LoadingUI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LoadingUI_C")
	}
	static class ULoadingUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoadingUI_C>();
	}
};
DUMPER7_ASSERTS_ULoadingUI_C;

}

