#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LookatInfoComponent

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LookatInfoComponent.LookatInfoComponent_C
// 0x0010 (0x00C0 - 0x00B0)
class ULookatInfoComponent_C final : public UActorComponent
{
public:
	class FString                                 Name_0;                                            // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LookatInfoComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LookatInfoComponent_C")
	}
	static class ULookatInfoComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULookatInfoComponent_C>();
	}
};
DUMPER7_ASSERTS_ULookatInfoComponent_C;

}

