#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapSelectUI

#include "Basic.hpp"

#include "MapSelectUI_classes.hpp"
#include "MapSelectUI_parameters.hpp"


namespace SDK
{

// Function MapSelectUI.MapSelectUI_C.ExecuteUbergraph_MapSelectUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::ExecuteUbergraph_MapSelectUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "ExecuteUbergraph_MapSelectUI");

	Params::MapSelectUI_C_ExecuteUbergraph_MapSelectUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.EventPreviewMap
// (BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::EventPreviewMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "EventPreviewMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.TryBuyMap
// (BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::TryBuyMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "TryBuyMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.OnSteamInventoryUpdated
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FSteamItemDetails>& Items                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMapSelectUI_C::OnSteamInventoryUpdated(const TArray<struct FSteamItemDetails>& Items)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "OnSteamInventoryUpdated");

	Params::MapSelectUI_C_OnSteamInventoryUpdated Parms{};

	Parms.Items = std::move(Items);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.RefreshOnInventory
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSteamInventoryFullUpdate& Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UMapSelectUI_C::RefreshOnInventory(const struct FSteamInventoryFullUpdate& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "RefreshOnInventory");

	Params::MapSelectUI_C_RefreshOnInventory Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Tick");

	Params::MapSelectUI_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.BndEvt__MapSelectUI_PreviewMapButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMapSelectUI_C::BndEvt__MapSelectUI_PreviewMapButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "BndEvt__MapSelectUI_PreviewMapButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.OnUpdateAllSteamInventory
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::OnUpdateAllSteamInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "OnUpdateAllSteamInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.GrantCoinPacks
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::GrantCoinPacks()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GrantCoinPacks");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.UpdateWhenResultIsFinished
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSteamInventoryResult&     Result                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::UpdateWhenResultIsFinished(const struct FSteamInventoryResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "UpdateWhenResultIsFinished");

	Params::MapSelectUI_C_UpdateWhenResultIsFinished Parms{};

	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.RefreshInventory
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::RefreshInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "RefreshInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.BndEvt__MapSelectUI_CoinBuyButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMapSelectUI_C::BndEvt__MapSelectUI_CoinBuyButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "BndEvt__MapSelectUI_CoinBuyButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.CloseMapSelect
// (BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::CloseMapSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "CloseMapSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMapSelectUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.UpdateMaps
// (BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::UpdateMaps()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "UpdateMaps");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.FocusOnMap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Map                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::FocusOnMap(class UClass* Map)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "FocusOnMap");

	Params::MapSelectUI_C_FocusOnMap Parms{};

	Parms.Map = Map;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.BndEvt__MapSelectUI_Button_69_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMapSelectUI_C::BndEvt__MapSelectUI_Button_69_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "BndEvt__MapSelectUI_Button_69_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.PreviewItem
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemInfo                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SalePrice                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::PreviewItem(class UClass* ItemInfo, int32 SalePrice)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "PreviewItem");

	Params::MapSelectUI_C_PreviewItem Parms{};

	Parms.ItemInfo = ItemInfo;
	Parms.SalePrice = SalePrice;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.CancelDrag
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::CancelDrag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "CancelDrag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.DragItemFromCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::DragItemFromCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "DragItemFromCategory");

	Params::MapSelectUI_C_DragItemFromCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.ChangeCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::ChangeCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "ChangeCategory");

	Params::MapSelectUI_C_ChangeCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapSelectUI.MapSelectUI_C.RemoveloadoutCategory
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::RemoveloadoutCategory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "RemoveloadoutCategory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.Remove
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::Remove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Remove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetText_0");

	Params::MapSelectUI_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetBrush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UMapSelectUI_C::GetBrush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetBrush_0");

	Params::MapSelectUI_C_GetBrush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.Get_EstimatedTake_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::Get_EstimatedTake_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Get_EstimatedTake_Text_0");

	Params::MapSelectUI_C_Get_EstimatedTake_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.Get_DifficultiText_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::Get_DifficultiText_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Get_DifficultiText_Text_0");

	Params::MapSelectUI_C_Get_DifficultiText_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetText_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::GetText_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetText_1");

	Params::MapSelectUI_C_GetText_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetBrush_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UMapSelectUI_C::GetBrush_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetBrush_1");

	Params::MapSelectUI_C_GetBrush_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.Get_CoinBuyButton_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UMapSelectUI_C::Get_CoinBuyButton_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Get_CoinBuyButton_Visibility_0");

	Params::MapSelectUI_C_Get_CoinBuyButton_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetText_2
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::GetText_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetText_2");

	Params::MapSelectUI_C_GetText_2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetText_3
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::GetText_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetText_3");

	Params::MapSelectUI_C_GetText_3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UMapSelectUI_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetColorAndOpacity_0");

	Params::MapSelectUI_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.SetRandomNumber
// (Public, BlueprintCallable, BlueprintEvent)

void UMapSelectUI_C::SetRandomNumber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "SetRandomNumber");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapSelectUI.MapSelectUI_C.Get_SaleOverlay_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UMapSelectUI_C::Get_SaleOverlay_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Get_SaleOverlay_Visibility_0");

	Params::MapSelectUI_C_Get_SaleOverlay_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.GetText_4
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapSelectUI_C::GetText_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetText_4");

	Params::MapSelectUI_C_GetText_4 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapSelectUI.MapSelectUI_C.Get Map Coin Price
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Map                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Price                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapSelectUI_C::Get_Map_Coin_Price(class UClass* Map, int32* Price)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "Get Map Coin Price");

	Params::MapSelectUI_C_Get_Map_Coin_Price Parms{};

	Parms.Map = Map;

	UObject::ProcessEvent(Func, &Parms);

	if (Price != nullptr)
		*Price = Parms.Price;
}


// Function MapSelectUI.MapSelectUI_C.GetMapOrder
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UMapSelectUIChild_C*>*     Out                                                    (Parm, OutParm, ContainsInstancedReference)

void UMapSelectUI_C::GetMapOrder(TArray<class UMapSelectUIChild_C*>* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "GetMapOrder");

	Params::MapSelectUI_C_GetMapOrder Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = std::move(Parms.Out);
}


// Function MapSelectUI.MapSelectUI_C.OnGetSteamInventoryItems
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSteamItemDetails>*       Items                                                  (Parm, OutParm)

void UMapSelectUI_C::OnGetSteamInventoryItems(TArray<struct FSteamItemDetails>* Items)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapSelectUI_C", "OnGetSteamInventoryItems");

	Params::MapSelectUI_C_OnGetSteamInventoryItems Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Items != nullptr)
		*Items = std::move(Parms.Items);
}

}

