#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuShelf_BasicDrill

#include "Basic.hpp"

#include "MenuShelf_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MenuShelf_BasicDrill.MenuShelf_BasicDrill_C
// 0x0020 (0x0258 - 0x0238)
class AMenuShelf_BasicDrill_C final : public AMenuShelf_base_C
{
public:
	class UStaticMeshComponent*                   Drill_Drill3;                                      // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Drill_Drill1;                                      // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Drill_Drill;                                       // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh_0;                                      // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MenuShelf_BasicDrill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MenuShelf_BasicDrill_C")
	}
	static class AMenuShelf_BasicDrill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMenuShelf_BasicDrill_C>();
	}
};
DUMPER7_ASSERTS_AMenuShelf_BasicDrill_C;

}

