#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuShelf_BatteringRam

#include "Basic.hpp"

#include "MenuShelf_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MenuShelf_BatteringRam.MenuShelf_BatteringRam_C
// 0x0008 (0x0240 - 0x0238)
class AMenuShelf_BatteringRam_C final : public AMenuShelf_base_C
{
public:
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MenuShelf_BatteringRam_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MenuShelf_BatteringRam_C")
	}
	static class AMenuShelf_BatteringRam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMenuShelf_BatteringRam_C>();
	}
};
DUMPER7_ASSERTS_AMenuShelf_BatteringRam_C;

}

