#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuShelf_base

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MenuShelf_base.MenuShelf_base_C
// 0x0018 (0x0238 - 0x0220)
class AMenuShelf_base_C : public AActor
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MenuShelf_base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MenuShelf_base_C")
	}
	static class AMenuShelf_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMenuShelf_base_C>();
	}
};
DUMPER7_ASSERTS_AMenuShelf_base_C;

}

