#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MessagePopup

#include "Basic.hpp"


namespace SDK::Params
{

// Function MessagePopup.MessagePopup_C.ExecuteUbergraph_MessagePopup
// 0x0004 (0x0004 - 0x0000)
struct MessagePopup_C_ExecuteUbergraph_MessagePopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MessagePopup_C_ExecuteUbergraph_MessagePopup;

}

