#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Guard

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "NPCBase_classes.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Guard.NPC_Guard_C
// 0x0160 (0x06A0 - 0x0540)
class ANPC_Guard_C final : public ANPCBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_NPC_Guard_C;                        // 0x0540(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPhysicsConstraintComponent*            PhysicsConstraint;                                 // 0x0548(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Sphere;                                            // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USteamStatComponent_C*                  SteamStatComponent;                                // 0x0558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       EscortSphere;                                      // 0x0560(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   EscortRing;                                        // 0x0568(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    EscortSpring;                                      // 0x0570(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Hat;                                               // 0x0578(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        PhoneSpawnArrow;                                   // 0x0580(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPawnSensingComponent*                  PawnSensing;                                       // 0x0588(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        GunLocation;                                       // 0x0590(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   GunBP;                                             // 0x0598(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAlertComponent_C*                      AlertComponent;                                    // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHeavyPickupComponent_C*                RagdollPickupComponent;                            // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPickupItemComponent_C*                 PickupItemComponent;                               // 0x05B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpottedHighlightcomponent_C*           SpottedHighlightcomponent;                         // 0x05B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotPlayerComponent_C*                 SpotPlayerComponent;                               // 0x05C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   SenseActor;                                        // 0x05C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Alpha_3B178F704D255F5D3990C2837E28D2EF; // 0x05D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_3B178F704D255F5D3990C2837E28D2EF; // 0x05D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5D5[0x3];                                      // 0x05D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x05D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Armed_;                                            // 0x05E0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5E1[0x7];                                      // 0x05E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Investigate_Reason;                                // 0x05E8(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          patrolling_;                                       // 0x05F8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Investigating_;                                    // 0x05F9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5FA[0x6];                                      // 0x05FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APoliceGunBase_C*                       GunActor;                                          // 0x0600(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_608[0x8];                                      // 0x0608(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             HomeTransform;                                     // 0x0610(0x0030)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	TArray<class AGuardPatrolPoint_C*>            PatrolPoints;                                      // 0x0640(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         CurrentPatrolPoint;                                // 0x0650(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Escorting_;                                        // 0x0654(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Alert_;                                            // 0x0655(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_656[0x2];                                      // 0x0656(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCharacter_C*                     TargetPlayer;                                      // 0x0658(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Sensing_;                                          // 0x0660(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_661[0x7];                                      // 0x0661(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGuardmanager_C*                        Manager;                                           // 0x0668(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CameraWatcher_;                                    // 0x0670(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_671[0x7];                                      // 0x0671(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCharacter_C*                     EscortingPlayer;                                   // 0x0678(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 AttachedKeycard;                                   // 0x0680(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          EMPed;                                             // 0x0688(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_689[0x7];                                      // 0x0689(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           EMPTimer;                                          // 0x0690(0x0008)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_NPC_Guard(int32 EntryPoint);
	void OnEMP(float Duration);
	void AttachKeycardMulti();
	void BreakKeycardConstraint(class AActor* Player, const struct FVector& Pickuplocation, const struct FRotator& PickupRotation, const struct FVector& HitLocation);
	void AttachKeycardServer();
	void BndEvt__NPC_Guard_Sphere_K2Node_ComponentBoundEvent_8_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void EscortRingVisible(bool Visible_);
	void MoveToEscortPoint();
	void BndEvt__NPC_Guard_EscortSphere_K2Node_ComponentBoundEvent_7_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__NPC_Guard_EscortSphere_K2Node_ComponentBoundEvent_6_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void EscortPlayer(class APlayerCharacter_C* Player);
	void SpawnPhone(class AActor* Player);
	void IgnoreAllCams();
	void BndEvt__NPC_Guard_CapsuleComponent_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void SendGuardToInvestigateCamera(const struct FVector& Location, class ACameraBP_C* Camera);
	void SetupCameraWatcher();
	void BndEvt__NPC_Guard_PawnSensing_K2Node_ComponentBoundEvent_2_HearNoiseDelegate__DelegateSignature(class APawn* Instigator_0, const struct FVector& Location, float Volume);
	void BndEvt__NPC_Guard_AlertComponent_K2Node_ComponentBoundEvent_5_NearbyNoise__DelegateSignature(const struct FVector& Location, float InvestigationDuration);
	void BndEvt__NPC_Guard_AlertComponent_K2Node_ComponentBoundEvent_3_OnAlarmtriggered__DelegateSignature();
	void ShootShock(class AActor* Instigator_0);
	void BndEvt__NPC_Guard_DamageComponent_K2Node_ComponentBoundEvent_1_Damage__DelegateSignature(int32 Amount, class FName Bone, const struct FVector& HitLocation, const struct FVector& StartLocation, class AActor* Instigator_0);
	void Shoot();
	void MoveToTarget();
	void FindTarget();
	void SmoothRotate(const struct FRotator& Rotation);
	void SetupPatrolPoints();
	void Patrol();
	void MoveHome();
	void ArrestPlayer(class APlayerCharacter_C* Player);
	void Setup_gun();
	void AlertGuardSelf();
	void ArmSelf();
	void OnDeath(class AActor* Player);
	void InvestigateWarning(const struct FVector& Location, const class FString& InvestigateReason);
	void InvestigateQuestion(const struct FVector& Location, float Duration);
	void BndEvt__NPC_Guard_SpotPlayerComponent_K2Node_ComponentBoundEvent_0_PlayerSpotted__DelegateSignature(class APawn* Player);
	void See_pawn(class APawn* Pawn);
	void FindNearestGuardAsActor(class AActor* GuardActor, float Distance);
	void OnSuccess_D4CF885043E71FB6876C1D9B6A317D0A(EPathFollowingResult MovementResult);
	void OnFail_D4CF885043E71FB6876C1D9B6A317D0A(EPathFollowingResult MovementResult);
	void OnSuccess_A69D7BC4402347B7ED18EDBBC193E7FD(EPathFollowingResult MovementResult);
	void OnFail_A69D7BC4402347B7ED18EDBBC193E7FD(EPathFollowingResult MovementResult);
	void OnSuccess_B6375C454B85D7A885195190AC05F5DD(EPathFollowingResult MovementResult);
	void OnFail_B6375C454B85D7A885195190AC05F5DD(EPathFollowingResult MovementResult);
	void OnSuccess_04A09ABC47BF8D5B9EA57399A9A932E4(EPathFollowingResult MovementResult);
	void OnFail_04A09ABC47BF8D5B9EA57399A9A932E4(EPathFollowingResult MovementResult);
	void OnSuccess_9A07A5AF4DE71869C1B1FA8D32BFBDEF(EPathFollowingResult MovementResult);
	void OnFail_9A07A5AF4DE71869C1B1FA8D32BFBDEF(EPathFollowingResult MovementResult);
	void OnSuccess_DE87B8E6433856E2A7A695A355C59AC3(EPathFollowingResult MovementResult);
	void OnFail_DE87B8E6433856E2A7A695A355C59AC3(EPathFollowingResult MovementResult);
	void OnSuccess_86C42EF74AA8DBBBB3067FB3927DD997(EPathFollowingResult MovementResult);
	void OnFail_86C42EF74AA8DBBBB3067FB3927DD997(EPathFollowingResult MovementResult);
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void UserConstructionScript();
	void FindCurrentPatrolPoint(class AGuardPatrolPoint_C** Point, bool* Last_point_);
	void FindNon_DownedPlayer(class APlayerCharacter_C** Player, bool* Found_);
	void ShootPlayer();
	void FindClosestGuard(class AActor* Closest_to, float max_distance, class ANPC_Guard_C** Guard, float* Distance_to);
	void LooseHat();
	void FindClosestGuardOnPath(const struct FVector& Location, class ANPC_Guard_C** ClosestGuard, float* Distance, struct FVector* ProjectedLocation);
	void UpdateAttachedKeycardLocation();
	void EMPTime();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_Guard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_Guard_C")
	}
	static class ANPC_Guard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Guard_C>();
	}
};
DUMPER7_ASSERTS_ANPC_Guard_C;

}

