#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPCInterface.NPCInterface_C
// 0x0000 (0x0000 - 0x0000)
class INPCInterface_C final
{
public:
	void CantOpenDoor();
	void RagdollPickedUp(bool Picked_up_);
	void PoliceAlerted();
	void SpawnAmmo(const struct FVector& Location, int32 Amount);
	void DestroyOldestPoliceBody();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPCInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPCInterface_C")
	}
	static class INPCInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<INPCInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_INPCInterface_C;

}

