#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickupItemBaseInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PickupItemBaseInterface.PickupItemBaseInterface_C
// 0x0000 (0x0000 - 0x0000)
class IPickupItemBaseInterface_C final
{
public:
	void OnPickupInterfaceCall();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PickupItemBaseInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PickupItemBaseInterface_C")
	}
	static class IPickupItemBaseInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPickupItemBaseInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IPickupItemBaseInterface_C;

}

