#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pistol_11A1

#include "Basic.hpp"

#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pistol_11A1.Pistol_11A1_C
// 0x0008 (0x0338 - 0x0330)
class APistol_11A1_C final : public AGunBase_C
{
public:
	class UBoxComponent*                          CollisionBox1;                                     // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Pistol_11A1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Pistol_11A1_C")
	}
	static class APistol_11A1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APistol_11A1_C>();
	}
};
DUMPER7_ASSERTS_APistol_11A1_C;

}

