#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pistol_GT17

#include "Basic.hpp"


namespace SDK::Params
{

// Function Pistol_GT17.Pistol_GT17_C.UserConstructionScript
// 0x0001 (0x0001 - 0x0000)
struct Pistol_GT17_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Pistol_GT17_C_UserConstructionScript;

}

