#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pistol_UP99

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pistol_UP99.Pistol_UP99_C
// 0x0010 (0x0340 - 0x0330)
class APistol_UP99_C final : public AGunBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Pistol_UP99_C;                      // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          CollisionBox1;                                     // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Pistol_UP99(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Pistol_UP99_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Pistol_UP99_C")
	}
	static class APistol_UP99_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APistol_UP99_C>();
	}
};
DUMPER7_ASSERTS_APistol_UP99_C;

}

