#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PoliceGun_m245

#include "Basic.hpp"

#include "PoliceGunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PoliceGun_m245.PoliceGun_m245_C
// 0x0000 (0x0280 - 0x0280)
class APoliceGun_m245_C final : public APoliceGunBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PoliceGun_m245_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PoliceGun_m245_C")
	}
	static class APoliceGun_m245_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APoliceGun_m245_C>();
	}
};
DUMPER7_ASSERTS_APoliceGun_m245_C;

}

