#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PoliceGun_Glock

#include "Basic.hpp"

#include "PoliceGunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PoliceGun_Glock.PoliceGun_Glock_C
// 0x0000 (0x0280 - 0x0280)
class APoliceGun_Glock_C final : public APoliceGunBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PoliceGun_Glock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PoliceGun_Glock_C")
	}
	static class APoliceGun_Glock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APoliceGun_Glock_C>();
	}
};
DUMPER7_ASSERTS_APoliceGun_Glock_C;

}

