#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RestrictedAreaVolume

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RestrictedAreaVolume.RestrictedAreaVolume_C
// 0x0020 (0x0240 - 0x0220)
class ARestrictedAreaVolume_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          ArrestWarning_;                                    // 0x0238(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_RestrictedAreaVolume(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveActorEndOverlap(class AActor* OtherActor);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void IsInSuperRestricted_(class APlayerCharacter_C* Player, bool* Arrest_, bool* In_restricted_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RestrictedAreaVolume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RestrictedAreaVolume_C")
	}
	static class ARestrictedAreaVolume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARestrictedAreaVolume_C>();
	}
};
DUMPER7_ASSERTS_ARestrictedAreaVolume_C;

}

