#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rifle_BPR28

#include "Basic.hpp"

#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Rifle_BPR28.Rifle_BPR28_C
// 0x0010 (0x0340 - 0x0330)
class ARifle_BPR28_C final : public AGunBase_C
{
public:
	class UBoxComponent*                          CollisionBox1;                                     // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Scope_front;                                       // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Rifle_BPR28_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Rifle_BPR28_C")
	}
	static class ARifle_BPR28_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARifle_BPR28_C>();
	}
};
DUMPER7_ASSERTS_ARifle_BPR28_C;

}

