#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RobberCameraManager

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RobberCameraManager.RobberCameraManager_C
// 0x0000 (0x2810 - 0x2810)
class ARobberCameraManager_C final : public APlayerCameraManager
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RobberCameraManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RobberCameraManager_C")
	}
	static class ARobberCameraManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARobberCameraManager_C>();
	}
};
DUMPER7_ASSERTS_ARobberCameraManager_C;

}

