#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_pistol_RedDot_2

#include "Basic.hpp"

#include "Attachment_scope_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Scope_pistol_RedDot_2.Scope_pistol_RedDot_2_C
// 0x0008 (0x0278 - 0x0270)
class AScope_pistol_RedDot_2_C final : public AAttachment_scope_base_C
{
public:
	class UStaticMeshComponent*                   Plane;                                             // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Scope_pistol_RedDot_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Scope_pistol_RedDot_2_C")
	}
	static class AScope_pistol_RedDot_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AScope_pistol_RedDot_2_C>();
	}
};
DUMPER7_ASSERTS_AScope_pistol_RedDot_2_C;

}

