#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SensingActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SensingActor.SensingActor_C
// 0x0018 (0x0298 - 0x0280)
class ASensingActor_C final : public APawn
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPawnSensingComponent*                  PawnSensing;                                       // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SensingActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SensingActor_C")
	}
	static class ASensingActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASensingActor_C>();
	}
};
DUMPER7_ASSERTS_ASensingActor_C;

}

