#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Setup_map_base

#include "Basic.hpp"

#include "ShopItem_Map_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Setup_map_base.Setup_map_base_C
// 0x0000 (0x02D8 - 0x02D8)
class ASetup_map_base_C : public AShopItem_Map_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Setup_map_base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Setup_map_base_C")
	}
	static class ASetup_map_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASetup_map_base_C>();
	}
};
DUMPER7_ASSERTS_ASetup_map_base_C;

}

