#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopItem_Emote_base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShopItem_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopItem_Emote_base.ShopItem_Emote_base_C
// 0x0020 (0x0290 - 0x0270)
class AShopItem_Emote_base_C : public AShopItem_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      Animation;                                         // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DropsItem_;                                        // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          StopSimulatePhysics_;                              // 0x0289(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ShopItem_Emote_base(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShopItem_Emote_base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShopItem_Emote_base_C")
	}
	static class AShopItem_Emote_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopItem_Emote_base_C>();
	}
};
DUMPER7_ASSERTS_AShopItem_Emote_base_C;

}

