#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopItem_WeaponMod_base

#include "Basic.hpp"

#include "ShopItem_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopItem_WeaponMod_base.ShopItem_WeaponMod_base_C
// 0x0008 (0x0278 - 0x0270)
class AShopItem_WeaponMod_base_C : public AShopItem_Base_C
{
public:
	class UClass*                                 Attachment;                                        // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShopItem_WeaponMod_base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShopItem_WeaponMod_base_C")
	}
	static class AShopItem_WeaponMod_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopItem_WeaponMod_base_C>();
	}
};
DUMPER7_ASSERTS_AShopItem_WeaponMod_base_C;

}

