#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopItem_WeaponMod_N1A_CompactVerticalGrip

#include "Basic.hpp"

#include "ShopItem_WeaponMod_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopItem_WeaponMod_N1A_CompactVerticalGrip.ShopItem_WeaponMod_N1A_CompactVerticalGrip_C
// 0x0000 (0x0278 - 0x0278)
class AShopItem_WeaponMod_N1A_CompactVerticalGrip_C final : public AShopItem_WeaponMod_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShopItem_WeaponMod_N1A_CompactVerticalGrip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShopItem_WeaponMod_N1A_CompactVerticalGrip_C")
	}
	static class AShopItem_WeaponMod_N1A_CompactVerticalGrip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopItem_WeaponMod_N1A_CompactVerticalGrip_C>();
	}
};
DUMPER7_ASSERTS_AShopItem_WeaponMod_N1A_CompactVerticalGrip_C;

}

