#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_ToughSkin_Tier2

#include "Basic.hpp"

#include "Skill_ToughSkin_Tier1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_ToughSkin_Tier2.Skill_ToughSkin_Tier2_C
// 0x0000 (0x00E0 - 0x00E0)
class USkill_ToughSkin_Tier2_C final : public USkill_ToughSkin_Tier1_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Skill_ToughSkin_Tier2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Skill_ToughSkin_Tier2_C")
	}
	static class USkill_ToughSkin_Tier2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_ToughSkin_Tier2_C>();
	}
};
DUMPER7_ASSERTS_USkill_ToughSkin_Tier2_C;

}

