#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_SharpShooter_Tier3

#include "Basic.hpp"


namespace SDK::Params
{

// Function Skill_SharpShooter_Tier3.Skill_SharpShooter_Tier3_C.ExecuteUbergraph_Skill_SharpShooter_Tier3
// 0x0004 (0x0004 - 0x0000)
struct Skill_SharpShooter_Tier3_C_ExecuteUbergraph_Skill_SharpShooter_Tier3 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Skill_SharpShooter_Tier3_C_ExecuteUbergraph_Skill_SharpShooter_Tier3;

}

