#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkinNotifPreview

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "RarityNum_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SkinNotifPreview.SkinNotifPreview_C
// 0x0018 (0x0278 - 0x0260)
class USkinNotifPreview_C final : public UUserWidget
{
public:
	class UImage*                                 Image_68;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Rarity;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UClass*                                 Item;                                              // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	struct FLinearColor Get_Rarity_ColorAndOpacity_0();
	struct FSlateBrush GetBrush_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SkinNotifPreview_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SkinNotifPreview_C")
	}
	static class USkinNotifPreview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkinNotifPreview_C>();
	}
};
DUMPER7_ASSERTS_USkinNotifPreview_C;

}

