#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpottedHighlightcomponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SpottedHighlightcomponent.SpottedHighlightcomponent_C
// 0x0010 (0x00C0 - 0x00B0)
class USpottedHighlightcomponent_C : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          CanHighlight_;                                     // 0x00B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          WarningHighlight_;                                 // 0x00B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          AlarmWarning_;                                     // 0x00BA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_SpottedHighlightcomponent(int32 EntryPoint);
	void UnHighlightMesh();
	void HighlightMesh();
	void HighlightChange(bool Highlight_, bool Warning_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SpottedHighlightcomponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpottedHighlightcomponent_C")
	}
	static class USpottedHighlightcomponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpottedHighlightcomponent_C>();
	}
};
DUMPER7_ASSERTS_USpottedHighlightcomponent_C;

}

