#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamFriendOptions

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AdvancedSessions_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SteamFriendOptions.SteamFriendOptions_C
// 0x0098 (0x02F8 - 0x0260)
class USteamFriendOptions_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Invite;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             InviteText;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                JoinGame;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             jointext;                                          // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ViewProfile;                                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FBPFriendInfo                          FriendInfo;                                        // 0x0290(0x0068)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void ExecuteUbergraph_SteamFriendOptions(int32 EntryPoint);
	void BndEvt__SteamFriendOptions_ViewProfile_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SteamFriendOptions_JoinGame_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SteamFriendOptions_Invite_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnMouseCaptureLost();
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	void Construct();
	void OnSuccess_1783753349D322B589CE1C8EB8F80925(const TArray<struct FBlueprintSessionResult>& SessionInfo);
	void OnFailure_1783753349D322B589CE1C8EB8F80925(const TArray<struct FBlueprintSessionResult>& SessionInfo);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SteamFriendOptions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteamFriendOptions_C")
	}
	static class USteamFriendOptions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamFriendOptions_C>();
	}
};
DUMPER7_ASSERTS_USteamFriendOptions_C;

}

