#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Suppressor_pistol

#include "Basic.hpp"

#include "Attachment_Barrel_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Suppressor_pistol.Suppressor_pistol_C
// 0x0000 (0x0260 - 0x0260)
class ASuppressor_pistol_C final : public AAttachment_Barrel_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Suppressor_pistol_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Suppressor_pistol_C")
	}
	static class ASuppressor_pistol_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASuppressor_pistol_C>();
	}
};
DUMPER7_ASSERTS_ASuppressor_pistol_C;

}

