#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tool_Grenade_base

#include "Basic.hpp"

#include "PickupItem_base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tool_Grenade_base.Tool_Grenade_base_C
// 0x0048 (0x02A0 - 0x0258)
class ATool_Grenade_base_C : public APickupItem_base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Tool_Grenade_base_C;                // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_SoundOcclusionComponent_C*          BP_SoundOcclusionComponent;                        // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Grenade_Handle;                             // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Grenade_Pin;                                // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USusItemComponent_C*                    SusItemComponent;                                  // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UComp_Explosive_C*                      Comp_Explosive;                                    // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TriggerTime;                                       // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Active_;                                           // 0x028C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          BreaksGlass_;                                      // 0x028D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_28E[0x2];                                      // 0x028E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             ActivationSound;                                   // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             ThrowSound;                                        // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Tool_Grenade_base(int32 EntryPoint);
	void HideAfterExplosion();
	void ExplodeServer();
	void HitGlass(class AActor* Object);
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ActivateGrenadeServer();
	void StartExplosiveMulti();
	void BndEvt__Tool_Grenade_base_PickupItemComponent_K2Node_ComponentBoundEvent_1_DropItem__DelegateSignature(class AActor* Player);
	void ActiveGrenadeMulti();
	void StartExplosiveServer();
	void BndEvt__Tool_Grenade_base_PickupItemComponent_K2Node_ComponentBoundEvent_0_InteractHolding__DelegateSignature(class AActor* Instigator_0, class AActor* Overlap);
	void OnRep_Active_();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tool_Grenade_base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Tool_Grenade_base_C")
	}
	static class ATool_Grenade_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATool_Grenade_base_C>();
	}
};
DUMPER7_ASSERTS_ATool_Grenade_base_C;

}

