#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ToolOwnerComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ToolOwnerComponent.ToolOwnerComponent_C
// 0x0020 (0x00D0 - 0x00B0)
class UToolOwnerComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void()>              Open;                                              // 0x00B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         Health;                                            // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ToolOwnerComponent(int32 EntryPoint);
	void TakeDamage(int32 Damage);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ToolOwnerComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ToolOwnerComponent_C")
	}
	static class UToolOwnerComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UToolOwnerComponent_C>();
	}
};
DUMPER7_ASSERTS_UToolOwnerComponent_C;

}

