#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tool_Grenade_Distraction

#include "Basic.hpp"

#include "Tool_Grenade_Distraction_classes.hpp"
#include "Tool_Grenade_Distraction_parameters.hpp"


namespace SDK
{

// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.ExecuteUbergraph_Tool_Grenade_Distraction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATool_Grenade_Distraction_C::ExecuteUbergraph_Tool_Grenade_Distraction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "ExecuteUbergraph_Tool_Grenade_Distraction");

	Params::Tool_Grenade_Distraction_C_ExecuteUbergraph_Tool_Grenade_Distraction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATool_Grenade_Distraction_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "ReceiveTick");

	Params::Tool_Grenade_Distraction_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.HideAfterExplosion
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ATool_Grenade_Distraction_C::HideAfterExplosion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "HideAfterExplosion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.ExplodeSoundMulti
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ATool_Grenade_Distraction_C::ExplodeSoundMulti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "ExplodeSoundMulti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.ExplodeServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ATool_Grenade_Distraction_C::ExplodeServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "ExplodeServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tool_Grenade_Distraction.Tool_Grenade_Distraction_C.TraceToPlayer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ATool_Grenade_Distraction_C::TraceToPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tool_Grenade_Distraction_C", "TraceToPlayer");

	UObject::ProcessEvent(Func, nullptr);
}

}

