#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WallBase_WindowsInner

#include "Basic.hpp"

#include "WallBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WallBase_WindowsInner.WallBase_WindowsInner_C
// 0x0000 (0x02D8 - 0x02D8)
class AWallBase_WindowsInner_C final : public AWallBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WallBase_WindowsInner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WallBase_WindowsInner_C")
	}
	static class AWallBase_WindowsInner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWallBase_WindowsInner_C>();
	}
};
DUMPER7_ASSERTS_AWallBase_WindowsInner_C;

}

