#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponBagSpawnPoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponBagSpawnPoint.WeaponBagSpawnPoint_C
// 0x0020 (0x0240 - 0x0220)
class AWeaponBagSpawnPoint_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Direction;                                         // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WeaponBagSpawnPoint(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeaponBagSpawnPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeaponBagSpawnPoint_C")
	}
	static class AWeaponBagSpawnPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeaponBagSpawnPoint_C>();
	}
};
DUMPER7_ASSERTS_AWeaponBagSpawnPoint_C;

}

