#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XN_1070

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass XN-1070.XN-1070_C
// 0x0010 (0x0340 - 0x0330)
class AXN_1070_C final : public AGunBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_XN_1070_C;                          // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          CollisionBox1;                                     // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_XN_1070(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("XN-1070_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"XN-1070_C")
	}
	static class AXN_1070_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AXN_1070_C>();
	}
};
DUMPER7_ASSERTS_AXN_1070_C;

}

